// Site presets: one design brief per trade, pasted into the build prompt after the master rules.
// Each one names a palette, two typefaces, the one signature element the page is remembered by, and a feeling.
// Edit them in settings; a saved edit wins over these defaults.
export const PRESETS = [
  {"name": "pools", "prompt": "Design direction for a pool builder website. Palette: sun-bleached white, deep water blue, one warm sand or terracotta accent used only for calls to action. Typography: wide confident grotesque display with an airy, readable body face. Signature element: a full-bleed water hero with the best photo under a soft caustic-light overlay, and a project gallery laid out like a backyard seen from above: big, few, breathing. The whole site should feel like the first cannonball of summer."},
  {"name": "remodel", "prompt": "Design direction for a remodeling contractor website. Palette: warm plaster white, walnut brown, one deep green or ink accent. Typography: refined editorial serif display with a precise grotesque body. Signature element: the photos shown as paired panels two per row, framed like finished rooms in a portfolio, and the process as three numbered steps (we talk, we build, you move back in). The whole site should feel like walking into the finished kitchen for the first time."},
  {"name": "construction", "prompt": "Design direction for a general contractor website. Palette: concrete gray, blueprint off-white, one high-vis accent used only on calls to action and key numbers. Typography: heavy industrial grotesque display with a plain legible body. Signature element: one giant hero photo of finished work with the headline set like stenciled site signage, and projects in a strict grid divided by thin blueprint rules. The whole site should feel like a jobsite at 7am, already moving."},
  {"name": "plumber", "prompt": "Design direction for a plumber website. Palette: Deep navy base, warm off-white, one safety-orange accent used only for the call button and key numbers. Typography: Bold condensed grotesque display like a hardware-store sign, with a highly readable body face. Signature element: The quote form styled as a carbon-copy job ticket with a perforated edge. The whole site should feel like a firm handshake."},
  {"name": "electrician", "prompt": "Design direction for a electrician website. Palette: Near-black with clean white and one circuit-yellow accent, used sparingly like warning tape. Typography: Technical grotesque with mono for panel labels and prices. Signature element: Services wired as a breaker-panel list, each row a labeled switch. The whole site should feel like a panel wired clean and labeled."},
  {"name": "hvac", "prompt": "Design direction for a hvac website. Palette: Cool slate blue meeting one warm ember accent: literal warm and cool sides of the palette. Typography: Sturdy grotesque display with a friendly body. Signature element: A temperature dial motif: the hero splits warm and cool, and the CTA sits at the comfortable middle. The whole site should feel like walking into perfect 72 degrees."},
  {"name": "roofing", "prompt": "Design direction for a roofing website. Palette: Charcoal shingle dark, weathered cream, one cedar accent. Typography: Slab display with structural weight, clean body. Signature element: Sections layered like overlapping shingle courses, each slightly overlapping the last. The whole site should feel like a roof you stop thinking about."},
  {"name": "landscaping", "prompt": "Design direction for a landscaping website. Palette: Rich soil brown and morning-light cream with one fresh green. Typography: Sturdy slab with a workwear feel. Signature element: A split-reveal hero that wipes between two of the photos as the visitor scrolls. The whole site should feel like Saturday morning, fresh-cut grass."},
  {"name": "pressure washing", "prompt": "Design direction for a pressure washing website. Palette: Deep wet-slate with one clean aqua accent and bright white. Typography: Rounded but solid grotesque. Signature element: The hero photo starts dim and grimy (a CSS filter) and wipes clean as the visitor scrolls. The whole site should feel like watching the driveway come back."},
  {"name": "cleaning", "prompt": "Design direction for a cleaning company website. Palette: Airy light base, deep trustworthy blue ink, one warm accent for the CTA. Typography: Friendly rounded grotesque, nothing corporate. Signature element: A three-step storyline (call, we come, it's done) as one horizontal strip; no prices unless given. The whole site should feel like weight off your shoulders."},
  {"name": "moving & junk", "prompt": "Design direction for a moving & junk removal website. Palette: Cardboard kraft neutrals, one tape-yellow accent, clean white. Typography: Bold friendly grotesque with big confident numbers. Signature element: A packing-label motif: quotes and steps styled like shipping labels with stamped dates. The whole site should feel like the truck pulling away, done."},
  {"name": "auto repair", "prompt": "Design direction for a auto repair website. Palette: Gunmetal and near-black with one muted copper accent for prices and the call button. Typography: Technical grotesque with mono for the spec readout. Signature element: Services as a torque-spec table in mono type, plus a gauge that fills to the Google rating as the visitor scrolls. The whole site should feel like torqued to spec."},
  {"name": "auto detailing", "prompt": "Design direction for a auto detailing website. Palette: Deep gloss black with one iced-silver-blue accent and mirror-white highlights. Typography: Sleek extended grotesque, minimal body. Signature element: A shine sweep that passes over the hero like light across fresh paint. The whole site should feel like showroom light on fresh wax."},
  {"name": "restaurant", "prompt": "Design direction for a restaurant (sit-down) website. Palette: Candlelit umber, warm cream, one deep red drawn from the food itself. Typography: Warm serif menus set like beautiful print. Signature element: A typographic hero set like a printed menu cover: the name, the cuisine, the address and the phone with dotted leaders; no dishes or prices unless given. The whole site should feel like the good table by the window."},
  {"name": "food truck", "prompt": "Design direction for a food truck website. Palette: One loud brand color from the truck wrap on near-black, cream for breathing room. Typography: Hand-painted-sign display with punchy weight. Signature element: A pinned 'find the truck' bar with the phone and the Facebook or Instagram link where they post locations. The whole site should feel like hearing the window slide open."},
  {"name": "coffee shop", "prompt": "Design direction for a coffee shop website. Palette: Espresso brown and steamed-milk cream, colors from the drinks themselves. Typography: Soft serif with hand-lettered warmth. Signature element: The address and phone treated like a note taped to the door. The whole site should feel like slow mornings, fast espresso."},
  {"name": "bakery", "prompt": "Design direction for a bakery website. Palette: Flour-dust cream, toasted crust brown, one berry accent. Typography: Rounded serif with warmth, like icing script shown restraint. Signature element: The photos presented as the glass case: a strip of square tiles under a chalkboard-style heading. The whole site should feel like warm bread at the counter."},
  {"name": "hair salon", "prompt": "Design direction for a hair salon website. Palette: Bone and soft black with one oxblood accent. Typography: High-contrast editorial serif at absurd sizes, tiny mono captions. Signature element: The services set like a magazine index with dotted leaders and kinetic type drifting on scroll; no prices unless given. The whole site should feel like walking out looking expensive."},
  {"name": "barbershop", "prompt": "Design direction for a barbershop website. Palette: Charcoal, chalk white, one barber-pole red used like a stripe, never a flood. Typography: Condensed vintage grotesque with mono ticket numbers. Signature element: Services presented as numbered chairs. The whole site should feel like hot towel, straight razor, no rush."},
  {"name": "nails & lashes", "prompt": "Design direction for a nails & lashes website. Palette: Porcelain neutral, ink black, one powder accent chosen from their actual photos. Typography: Elegant serif with fine hairline rules. Signature element: A swatch strip in the accent colors, with the photos rendered like polish chips. The whole site should feel like hands you can't stop looking at."},
  {"name": "tattoo", "prompt": "Design direction for a tattoo studio website. Palette: Near-black, paper white, one dried-ink red. Typography: One blackletter-adjacent display moment, engraved grotesque everywhere else. Signature element: The photos framed like flash sheets pinned to the wall. The whole site should feel like quiet needle hum, steady hands."},
  {"name": "gym", "prompt": "Design direction for a gym website. Palette: Chalkboard charcoal and chalk white, nothing neon. Typography: Massive condensed display: one line solid, one chalk-outlined. Signature element: The programs chalked in line by line as they scroll into view; no class times unless given. The whole site should feel like show up, we handle the rest."},
  {"name": "martial arts", "prompt": "Design direction for a martial arts website. Palette: Mat-dark base, canvas cream, one belt-gold accent. Typography: Disciplined grotesque with wide tracking, like a dojo crest. Signature element: The program laid out as a belt-progression path. The whole site should feel like bowing in, phone off."},
  {"name": "yoga / pilates", "prompt": "Design direction for a yoga / pilates website. Palette: Warm linen, eucalyptus green, deep slate ink. Typography: Light humanist serif with generous air. Signature element: A breath of whitespace: sections ease open on scroll; the services as a calm list, no timetable unless given. The whole site should feel like the exhale at the end of class."},
  {"name": "dental", "prompt": "Design direction for a dental office website. Palette: Warm paper white and soft sage with deep ink text, nothing harsh or clinical. Typography: Reassuring humanist serif with a friendly geometric body. Signature element: A 'your first visit' card built around the phone and address, treated as the star of the page; nothing invented about insurance. The whole site should feel like an exhale in the waiting room."},
  {"name": "chiro / pt", "prompt": "Design direction for a chiropractor / pt website. Palette: Clinical calm: warm white, steady slate blue, deep ink. Typography: Confident humanist grotesque. Signature element: A recovery timeline: visit one to feeling better, drawn as a simple path. The whole site should feel like standing up straight again."},
  {"name": "med spa", "prompt": "Design direction for a med spa website. Palette: Porcelain, deep evergreen ink, one champagne accent. Typography: Refined editorial serif with whisper-quiet captions. Signature element: Treatments as a quiet menu of results, no prices unless given, no asterisks. The whole site should feel like leaving lighter than you came."},
  {"name": "real estate", "prompt": "Design direction for a real estate agent website. Palette: Ivory and deep pine, more gallery than brochure. Typography: Elegant editorial serif at large sizes, tiny mono captions. Signature element: The photos dealt past like framed prints on a gallery wall. The whole site should feel like homes worth the drive."},
];

// Prompts shipped before the briefs above; a saved preset still carrying one of these gets upgraded.
export const OLD_PROMPTS = new Set([
  "One page for a residential pool builder. Lead with their best three photos full width, then services as short lines, then reviews pulled from Google, then a quote form. Warm, sunlit, confident. No stock photos. Phone number visible at every scroll position. Use {business}, {owner}, {phone}, {hours}, {services}, {reviews}, {photos}.",
  "One page for a remodel contractor. Before and after pairs first, two per row. Then the process in three steps, then reviews, then a quote form. Calm and precise. Use {business}, {owner}, {phone}, {hours}, {services}, {reviews}, {photos}.",
  "One page for a general contractor. Big hero photo of a finished job, then a short list of what they build, then recent projects as a grid, then reviews and a call button. Plain and solid, nothing clever. Use {business}, {owner}, {phone}, {hours}, {services}, {reviews}, {photos}.",
  "One page for a home services business. Phone number is the hero. Then the three most common jobs with a price range, then reviews, then service area. Fast to read on a phone. Use {business}, {owner}, {phone}, {hours}, {services}, {reviews}, {photos}."
]);

// Saved presets win; defaults they don't have are appended; an untouched old default is replaced by its new text.
export function mergePresets(saved) {
  if (!Array.isArray(saved) || !saved.length) return PRESETS;
  const byName = new Map(PRESETS.map((p) => [p.name, p]));
  const out = saved.map((p) => (OLD_PROMPTS.has(p.prompt) && byName.get(p.name) ? byName.get(p.name) : p));
  // 'services' was a catch-all that no longer exists; drop it only if it was never edited
  const kept = out.filter((p) => !(p.name === 'services' && OLD_PROMPTS.has(p.prompt)));
  const have = new Set(kept.map((p) => p.name));
  return [...kept, ...PRESETS.filter((p) => !have.has(p.name))];
}
